# Generated by Django 5.1.3 on 2024-11-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_outofoffice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='automation_server_ip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='automation_server_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='automation_servers_required',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='computer_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='computer_setup_status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='controller_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='controller_type',
            field=models.CharField(blank=True, choices=[('I2', 'I2 (Not Changing Controllers)'), ('SmartX', 'New SmartX')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='conversion_errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deployed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deployment_readiness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='dmp_conversion_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dmp_file_status',
            field=models.CharField(choices=[('Uploaded', 'Uploaded'), ('Not Uploaded', 'Not Uploaded')], default='Not Uploaded', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='ecos_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='enterprise_server_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='existing_ecos_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='graphics_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_conversion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='license_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='license_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='licenses_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='new_computer_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='new_computer_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='previous_system_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='service_tech_installing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='smartx_controllers_needed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='software_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
